sonar.projectKey=ha-organizer
sonar.projectName=HA Organizer
sonar.projectVersion=2026.8.0

sonar.sources=custom_components/ha_organizer
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8

sonar.coverage.exclusions=tests/**,custom_components/ha_organizer/brand/**
sonar.exclusions=custom_components/ha_organizer/brand/**
sonar.qualitygate.wait=true
